# Generated by Django 5.1.10 on 2025-07-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Employee_ID',
            field=models.ImageField(blank=True, null=True, upload_to='employees_id/'),
        ),
    ]
