from django.urls import path
from .views import (
    AccountTypeList,
    AccountTypeDetail,
    AccountList,
    AccountDetail,
    JournalEntryList,
    JournalEntryDetail,
    JournalEntryLineList,
    JournalEntryLineDetail,
    SupplierInvoiceList,
    SupplierInvoiceDetail,
    SupplierInvoiceLineList,
    SupplierInvoiceLineDetail,
    SupplierPaymentList,
    SupplierPaymentDetail,
    CustomerInvoiceList,
    CustomerInvoiceDetail,
    CustomerInvoiceLineList,
    CustomerInvoiceLineDetail,
    CustomerPaymentList,
    CustomerPaymentDetail,
    ExpenseList,
    ExpenseDetail,
    FinancialPeriodList,
    FinancialPeriodDetail,

)

urlpatterns = [
    path("AccountList/", AccountTypeList.as_view(), name="accountlist"),
    path("AccountList/<str:name>/", AccountTypeDetail.as_view(), name="account-detail"),
    path("Account/", AccountList.as_view(), name="accountlist"),
    path("Account/<str:name>/", AccountDetail.as_view(), name="account-detail"),
    path("JournalEntry/", JournalEntryList.as_view(), name="journalentrylist"),
    path("JournalEntry/<int:id>/", JournalEntryDetail.as_view(), name="journalentry-detail"),
    path("JournalEntryLine/", JournalEntryLineList.as_view(), name="journalentrylinelist"),
    path("JournalEntryLine/<int:id>/", JournalEntryLineDetail.as_view(), name="journalentryline-detail"),
    path("SupplierInvoice/", SupplierInvoiceList.as_view(), name="supplierinvoicelist"),
    path("SupplierInvoice/<int:id>/", SupplierInvoiceDetail.as_view(), name="supplierinvoice-detail"),
    path("SupplierInvoiceLine/", SupplierInvoiceLineList.as_view(), name="supplierinvoicelinelist"),
    path("SupplierInvoiceLine/<int:id>/", SupplierInvoiceLineDetail.as_view(), name="supplierinvoiceline-detail"),
    path("SupplierPayment/", SupplierPaymentList.as_view(), name="supplierpaymentlist"),
    path("SupplierPayment/<int:id>/", SupplierPaymentDetail.as_view(), name="supplierpayment-detail"),
    path("CustomerInvoice/", CustomerInvoiceList.as_view(), name="customerinvoicelist"),    
    path("CustomerInvoice/<int:id>/", CustomerInvoiceDetail.as_view(), name="customerinvoice-detail"),
    path("CustomerInvoiceLine/", CustomerInvoiceLineList.as_view(), name="customerinvoicelinelist"),    
    path("CustomerInvoiceLine/<int:id>/", CustomerInvoiceLineDetail.as_view(), name="customerinvoiceline-detail"),
    path("CustomerPayment/", CustomerPaymentList.as_view(), name="customerpaymentlist"),    
    path("CustomerPayment/<int:id>/", CustomerPaymentDetail.as_view(), name="customerpayment-detail"),
    path("Expense/", ExpenseList.as_view(), name="expenselist"),
    path("Expense/<int:id>/", ExpenseDetail.as_view(), name="expense-detail"),
    path("FinancialPeriod/", FinancialPeriodList.as_view(), name="financialperiodlist"),
    path("FinancialPeriod/<int:id>/", FinancialPeriodDetail.as_view(), name="financialperiod-detail"),
    

]
