# Generated by Django 5.2.4 on 2025-08-25 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('TA', 'Tenant Admin'), ('FM', 'Finance Manager'), ('HM', 'HRM Manager'), ('IM', 'Inventory Manager'), ('FE', 'Finance Member'), ('HE', 'HRM Member'), ('IE', 'Inventory Member')], max_length=2)),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['FM', 'HM', 'IM']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
