# Generated by Django 4.2.22 on 2025-06-09 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
