# Generated by Django 4.2.22 on 2025-06-09 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_client_created_on'),
        ('users', '0004_remove_customuser_tenant_delete_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_tenant_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.client'),
        ),
    ]
