# Generated by Django 4.2.22 on 2025-06-09 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_is_tenant_admin_customuser_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_tenant_admin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='tenant',
        ),
    ]
