# Generated by Django 4.2.22 on 2025-06-08 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='created_on',
        ),
    ]
